# Test against this version of Node.js
environment:
   matrix:
   - nodejs_version: "6"

# Install scripts.
install:
   - ps: Install-Product node $env:nodejs_version
   - npm install

# Post-install tests
test_scripts:
   #Output useful info for debugging
   - node --version
   - npm --version
   #Run tests
   - npm test

# Don't actually build
build: off
